[tool.pylint]
max-line-length = 88

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-docstring",      # Disable docstring requirements
    "too-few-public-methods", # Allow classes with few methods
    "too-many-arguments",
    "too-many-positional-arguments",
    "wrong-import-order",     # Already addressed by isort
]

[tool.mypy]
disable_error_code = ["import-untyped"]
