project_path: /path/to/this/repo
hydra_root: ${user_settings.project_path}/hydra
hydra_dir: ${user_settings.hydra_root}/${now:%Y-%m-%d}/${now:%H-%M-%S}
result_dir: ${user_settings.hydra_dir}

model_root: /path/to/models
dataset_root: /path/to/datasets
